# See https://github.com/SocialGouv/helm-charts/tree/master/charts/app

image:
  repository: $CI_REGISTRY_IMAGE
  tag: master

deployment:

  livenessProbe:
    initialDelaySeconds: 30
    path: /health
    periodSeconds: 15
  readinessProbe:
    initialDelaySeconds: 30
    path: /health
    periodSeconds: 15

  resources:
    limits:
      memory: 128Mi
    requests:
      memory: 64Mi

  env:
    - name: GITHUB_ORGANIZATION
      value: "${GITHUB_ORGANIZATION}"
    - name: HASURA_SECRET
      value: "${HASURA_SECRET}"
    - name: HASURA_URL
      value: "${HASURA_URL}"
    - name: NODE_ENV
      value: "production"
    - name: PORT
      value: "${PORT}"

ingress:
  enabled: true
