.deploy_standup_k8s: &deploy_stand_up
  image:
    name: $CI_REGISTRY/$IMAGE_INFRA_BASE_NAME/helm:$INFRA_HELM_VERSION
    entrypoint: [""]
  script:
    - helm init --client-only
    - helm repo add mas-incubateur https://socialgouv.github.io/helm-charts/
    - envsubst < .gitlab-ci/values.yaml > .gitlab-ci/values-${APP_NAME}.yaml
    - helm upgrade --install --wait --namespace standup-${NAMESPACE} --values=.gitlab-ci/values-${APP_NAME}.yaml ${HELM_RELEASE_NAME} mas-incubateur/webapp
  allow_failure: false

.deploy-standup-k8s-feature:
  <<: *deploy_stand_up
  before_script:
    - HASH_BRANCH_NAME=$(printf "$CI_COMMIT_REF_NAME" | sha1sum | cut -c1-5)
    - export INGRESS_ENVIRONMENT_PREFIX=$HASH_BRANCH_NAME.
    - export HELM_RELEASE_NAME=$APP_NAME-$HASH_BRANCH_NAME-$FEATURE_ENVIRONMENT_NAME
    - export HASH_BRANCH_NAME=-$HASH_BRANCH_NAME

.deploy-standup-k8s-master:
  <<: *deploy_stand_up
  before_script:
    - export HELM_RELEASE_NAME=$APP_NAME-$MASTER_ENVIRONMENT_NAME

.deploy-standup-k8s-preprod:
  <<: *deploy_stand_up
  before_script:
    - export HELM_RELEASE_NAME=$APP_NAME-$PREPROD_ENVIRONMENT_NAME

.deploy-standup-k8s-prod:
  <<: *deploy_stand_up
  before_script:
    - export HELM_RELEASE_NAME=$APP_NAME-$PROD_ENVIRONMENT_NAME
