kind: ConfigMap
apiVersion: v1
metadata:
  name: app-configmap
data:
  NODE_ENV: "production"
  PORT: "3000"
  POSTGRES_SSL: "true"
  GITHUB_ORGANIZATION: "SocialGouv"
  HASURA_URL: "https://hasura.carnets.fabrique.social.gouv.fr/v1/graphql"
