apiVersion: v2
name: socialgouv-autodevops
version: 1.0.0
appVersion: 1.0.0
home: https://github.com/SocialGouv
description: Helm template for Kubernetes
icon: https://avatars.githubusercontent.com/u/45039513?v=4
sources:
- https://github.com/SocialGouv/standup
maintainers:
- name: Fabrique numérique des Ministères Sociaux
  email: dsi-incubateur@sg.social.gouv.fr
dependencies:
- name: Classic frontend app
  version: 1.0.0
  repository: file://./charts/app
  condition: components.app