namespace: 
host: 
registry:
imageTag: 
ttl: 
rancherProjectId: my-cluser-id:my-project-id
gitBranch: my-awesome-branch
isProduction: false
isPreProduction: false
appPort: 8080
envSecretName: awesome-sealed-secret
envConfigName: awesome-configmap