apiVersion: v1
kind: ConfigMap
metadata:
  name: standup-configmap
  labels:
    application: standup
    owner: standup
    team: standup
  namespace: {{ .Values.namespace }}
data:
  NODE_ENV: production
  GITHUB_ORGANIZATION: SocialGouv
  HASURA_URL: https://hasura-carnets.fabrique.social.gouv.fr/v1/graphql
  MATOMO_SITE_ID: '30'
  MATOMO_URL: https://matomo.fabrique.social.gouv.fr/
