apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: standup
    application: standup
    owner: standup
    team: standup
  name: standup
  namespace: {{ .Values.namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: standup
  template:
    metadata:
      labels:
        app: standup
        application: standup
        component: nginx
        owner: standup
        team: standup
        cert: wildcard
    spec:
      containers:
        - image: >-
            {{ .Values.registry }}:{{ .Values.imageTag }}
          livenessProbe:
            failureThreshold: 6
            httpGet:
              path: /index.html
              port: http
            initialDelaySeconds: 30
            periodSeconds: 5
            timeoutSeconds: 5
          name: standup
          ports:
            - containerPort: 80
              name: http
          readinessProbe:
            failureThreshold: 15
            httpGet:
              path: /index.html
              port: http
            initialDelaySeconds: 0
            periodSeconds: 5
            successThreshold: 1
            timeoutSeconds: 1
          resources:
            limits:
              cpu: 500m
              memory: 128Mi
            requests:
              cpu: 5m
              memory: 32Mi
          startupProbe:
            failureThreshold: 12
            httpGet:
              path: /index.html
              port: http
            periodSeconds: 5
          envFrom:
            - secretRef:
                name: standup-sealed-secret
            - configMapRef:
                name: standup-configmap