apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    {{- if not .Values.isProduction }}
    sealedsecrets.bitnami.com/cluster-wide: 'true'
    {{- end }}
  name: app-sealed-secret
  namespace: {{ .Values.namespace }}
  labels:
    application: {{ .Chart.Name }}
spec:
  encryptedData:
    SENTRY_DSN: >-
      {{- if .Values.isProduction }}
      AgCeHyx1GrZOVOH0zNUtFYQXDOVI5b/JRBd9aG9FiPkVbJtcHSBoSvdQWu7ddGJ/QaIyd0XUKJKJAYCjQZ/tmR7p5hYVR8ye/gKGeBi61YkY1G6HKW7DDuJZZOatxl3I6XSlubrGTQRNLptT1v3Vt0S8KQhpeoX28VXw4P8PqUAbTMgi6Wj5gLR5TvpuptzWtm9+5U2+orw3ixtnVuqKUNPX79hbWQYu/AB2nNHmWs8PBZavl29+olCWWKnzY3gPdw3rpeobLDHougOC//lXXC4HptZaZ5yTPI5CacTRxTqvN+ZgDTw1Tc/klD0W4r2lhqezZtLigEILxnArksatuuL3HsRBxLvMBJDoBcClFa7U534uuTCsaReB2eMDW7fHFZIZHoJy+lnx+cOQg5BE5Oy7hwBle/oF/e0eR7Jy3pHs94MDK+Jm3o6FhOTwdUv0qJIg2Jo3bdbXPXSVPeQAVy0711TrQBF8eevb5d9J8CTTgvhorXJve5d7G/a4sCEtcNfoKXVzHkHN1tLF42KpDKd61tDYH7y9/OzvV3pgTuwJ7T/7QGxEU61WWt8xD8/GYAjT6GLeomcR6fcMYgmPHt32VlcP+I05FtY5T17V3jfvSoxIJInVjHFW/FXYWvpwMGzuJZhWsqqFPXeO2kLG+8uoVpRVEmP8zohfbhmxVrghfhgLDf+9iNeds4sm0uC/FdnMKqYUSmgxGKLNHThCGg7slMhy5Py98/pzwxgKh89swQKYvr7irTW9lOPVNDI91vtzneFuo0uBrtudhzuXWb9Cq9uyWcseYsjREg==
      {{- else if .Values.isPreProduction }}
      AgBdH6m/TJnT+pYS0hZtTUWCLzM2h+KEzpLunVsYoam0K7eWh413lDtrO8N3OpJLBHeZKF+sZh9j0s9oBeic11I51YGIIKXxszeyiUf9N2ZibrS5Yg1Jrp9blQhBwn8t/6I8vbCVVydmb8ynrqKvSPUObIDXz5cWo/w1i1lI0Jcjiti6/tTa7UeNw5u4HiYsOczCz3cmk/e6cgEdt7DzF+sK0VJBJjeXWmNyIGPThO/MPGxMAVwJpBOlqOchf0DGWglfBEVkvWYUOmurN3Mqc518heA8/y3OVuEYiflpK7ZUNu2Vok9frVBms8uL9MJaG3es77EqkSc2PV4F9ftGLJBBzVaNqHJgP3iBMWRjz+POB1h2eljxeAGfHzizK24hsSdeIsCzkzYCzWfaoPceMLLph1XGePSoDKerMR1/16MFfXcXIWSeJSYRp38UMaRWDyMQ4xjMHDBcnE7J7CR+ZMooAQkWvaRFBk0SkbwOvusz9+/a4/h/fLkq3N3CtEGP/uFHDQgbLO+C3P0wdu/ervMrXs2/Fg/XQBsYm0zAfVAEsthZbP2UZ+bb22xXPufYfkhwJhXeTIgOC6OmGHvpajQR/M8LcoyjXYPeBXN/bFZ7jlvzCwHjWbwQGtT3SmQa+MilfvGLia87o/RGMusn4FeGmTwXg1eCZBkSlded6thIat1OcJfyQkVXGQBN6VrPBiA3ep8+Fa+Xybyeuk0OUScY+XC/y3/5FYI1tTtjtlZT4B7iGpu9Zw1hBPcNAzGJEIHD5N1jWJK7aUnQWq/8sEx8k6t9oCn0INAHDQ==
      {{- else }}
      AgBApFjJq6o6w6lQA3/6LX9Hk7EhIQgz6y/uBZh7UegeYq/vtjmXjbbOJsNna2x30E6DCUMWNbqVne1lmgJaPJn0t4u5k0bs8pW7GLQwpLmRtE6005b+bjyqH4QNRCEriaOyQrjQldxW7/dqBQRLD1RCh6AGSacDxbEh7Dw8WaeBIvdq64tu1w4RVVCkjekLUR4MRjaTbK8QDYyHWGW3szHcrWGiV3MpLeNi+dXTzWPuVcWocRmjLQOTwv7Issfcj4A+GjoRpOherF0cYFlpO+nEPtDh+lr9lOTsTdWilb+woWCa9QrYxjuPBXVFosmKpUHeafpIKqhIAP2MGkcpBNxNAdwWB1cFsImgWNAl6883bBJ8FdiOn6BViZlyYD0fWRzVjNy39X0JgKeuQKvRkMpqbSrLGZts5ElPBzT458e3v/M/2mcIKXAtjTWxCYpmIqYP3HI90yBIYQYErYu5sbxKxUFpW6Bq+vwINxkuFu+kyIUmDDC+gjzTes1sf8D2QWIvXnvy87w946+1fnbzZuFlZzG6xf7DwomC1KRp0BFpxa3sPrcDdyGkvPNq9JTWmEpcUyJq9SEZGC0+hRiffBo+B5UeN7pCxQrTViIZZBEb54v61VOu7MSNH3gVQnR4aiAFgite5GAqxOqNaYybglef/WUdm4wL6C++jB2E5cNSpz3JWTk22sDfCvgRNcHbW/MpiQzRIBOrpGFqEHpE/TZ6JIplSxHZ1UF440hTOVLpO2PWSHToVQ1r3iY9/M6NcOtKdHdEShYrWSak0feMYlvN2ofXtXfbUlUbQw==
      {{- end }}
  template:
    metadata:
      annotations:
        {{- if not .Values.isProduction }}
        sealedsecrets.bitnami.com/cluster-wide: 'true'
        {{- end }}
      name: app-sealed-secret
      labels:
        application: {{ .Chart.Name }}
    type: Opaque