apiVersion: v1
kind: Service
metadata:
  annotations:
    kapp.k14s.io/disable-default-ownership-label-rules: ""
    kapp.k14s.io/disable-default-label-scoping-rules: ""
    kapp.k14s.io/delete-strategy: orphan
  labels:
    app: app
    application: {{ .Chart.Name }}
  name: app
  namespace: {{ .Values.namespace }}
spec:
  ports:
    - name: http
      port: {{ .Values.appPort }}
      targetPort: {{ .Values.appPort }}
  selector:
    app: app
  type: ClusterIP