kind: ConfigMap
apiVersion: v1
metadata:
  name: standup-configmap
data:
  NODE_ENV: "production"
  GITHUB_ORGANIZATION: "SocialGouv"
  HASURA_URL: "https://hasura-carnets.fabrique.social.gouv.fr/v1/graphql"
  MATOMO_SITE_ID: "30"
  MATOMO_URL: "https://matomo.fabrique.social.gouv.fr/"
