name: Build

on:
  push:
    branches: [alpha, beta, next]

jobs:
  build:
    name: Build & Register
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Node setup
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Yarn cache setup
        uses: c-hive/gha-yarn-cache@v1

      - name: App build
        run: |
          yarn --frozen-lockfile --prefer-offline
          yarn build
          yarn export

      - name: Create image labels and tags
        id: docker_meta
        uses: "crazy-max/ghaction-docker-meta@2e1a5c7fa42123697f82d479b551a1bbdb1bef88"
        with:
          images: ghcr.io/socialgouv/fabrique/standup
          labels: |
            org.opencontainers.image.title=standup
            org.opencontainers.image.documentation=https://github.com/SocialGouv/standup/tree/${{ github.sha }}
          tags: |
            type=sha
            type=ref,event=pr
            type=ref,event=branch
            type=semver,pattern={{version}}
            type=raw,value=sha-${{ github.sha }}
            type=semver,pattern={{major}}.{{minor}}

      - name: Set up Buildx
        id: buildx
        uses: docker/setup-buildx-action@master
        with:
          install: true

      - name: Registry authentication
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ secrets.SOCIALGROOVYBOT_NAME }}
          password: ${{ secrets.SOCIALGROOVYBOT_GHCR_PAT }}

      - name: Image build and register
        uses: docker/build-push-action@v2
        with:
          context: .
          push: 'true'
          builder: ${{ steps.buildx.outputs.name }}
          tags: "${{ steps.docker_meta.outputs.tags }}"
          labels: "${{ steps.docker_meta.outputs.labels }}"

      # - name: Image build and register
      #   uses: aevea/action-kaniko@master
      #   with:
      #     cache: true
      #     tag: ${{ github.sha }}
      #     image: ${{ secrets.HARBOR_PROJECT }}
      #     registry: ${{ secrets.HARBOR_REGISTRY }}
      #     username: ${{ secrets.HARBOR_USERNAME }}
      #     password: ${{ secrets.HARBOR_PASSWORD }}
      #     cache_registry: ${{ secrets.HARBOR_PROJECT }}/cache

      # - name: Trigger deployment
      #   uses: wei/curl@v1
      #   with:
      #     args: -X POST -F token=${{ secrets.GITLAB_TRIGGER_TOKEN }} -F ref=$GITHUB_REF -F "variables[DEPLOY]=true" https://gitlab.factory.social.gouv.fr/api/v4/projects/${{ secrets.GITLAB_PROJECT_ID }}/trigger/pipeline
