name: Build

on:
  push:
    branches: [master, alpha, beta, next]

jobs:
  build:
    name: Build & Register
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Node setup
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Yarn cache setup
        uses: c-hive/gha-yarn-cache@v1

      - name: App build
        run: |
          yarn --frozen-lockfile --prefer-offline
          yarn build
          yarn export

      - name: Image build and register
        uses: aevea/action-kaniko@master
        with:
          cache: true
          image: ${{ secrets.HARBOR_PROJECT }}
          cache_registry: fabrique/standupx/cache
          registry: ${{ secrets.HARBOR_REGISTRY }}
          username: ${{ secrets.HARBOR_USERNAME }}
          password: ${{ secrets.HARBOR_PASSWORD }}

      - name: Trigger deployment
        uses: wei/curl@v1
        with:
          args: -X POST -F token=${{ secrets.GITLAB_TRIGGER_TOKEN }} -F ref=$GITHUB_REF -F "variables[DEPLOY]=true" https://gitlab.factory.social.gouv.fr/api/v4/projects/${{ secrets.GITLAB_PROJECT_ID }}/trigger/pipeline
