name: Manifest

on:
  push:
    branches: [alpha, beta, next]

env:
  SOCIALGOUV_KUBE_INGRESS_BASE_DOMAIN: ${{ secrets.SOCIALGOUV_KUBE_INGRESS_BASE_DOMAIN }}

jobs:
  build:
    name: Generate k8s manifest
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Node setup
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Show env variables
        run: |
          echo GITHUB_REF: $GITHUB_REF
          echo GITHUB_SHA: $GITHUB_SHA
          echo SOCIALGOUV_KUBE_INGRESS_BASE_DOMAIN: $SOCIALGOUV_KUBE_INGRESS_BASE_DOMAIN

      - name: Run kosko generate
        run: |
          npx @socialgouv/k8s@1.9.0-alpha.7 > manifest.yml

      - name: Debug
        run: cat manifest.yml
