name: Release

on:
  push:
    branches:
      - master
      - alpha
      - beta
      - next
    # tags-ignore:
    #   - '**'

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, 'chore(release)')"
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: Node setup
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Yarn cache setup
        uses: c-hive/gha-yarn-cache@v1

      - name: Install dependencies
        run: yarn --frozen-lockfile --prefer-offline

      # - name: Run semantic release
      #   run: npx semantic-release
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.SOCIALGROOVYBOT_BOTO_PAT }}
      #     # GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Semantic Release
        id: semantic
        uses: cycjimmy/semantic-release-action@v2
        with:
          # dry_run: true
          semantic_version: 16
          extra_plugins: |
            @semantic-release/changelog@3.0.0
        env:
          GITHUB_TOKEN: ${{ secrets.SOCIALGROOVYBOT_BOTO_PAT }}
          # GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Debug
        if: steps.semantic.outputs.new_release_published == 'true'
        run: |
          git status
          ls -lah
          echo ${{ steps.semantic.outputs.new_release_version }}

      - name: Commit changes
        if: steps.semantic.outputs.new_release_published == 'true'
        uses: EndBug/add-and-commit@v7 # You can change this to use a specific version
        with:
          pull_strategy: 'NO-PULL'
          add: 'CHANGELOG.md package.json'
          message: "chore(release): ${{ steps.semantic.outputs.new_release_version }} [skip ci]"
        # run: |
        #   git config user.email "${{ secrets.SOCIALGROOVYBOT_EMAIL }}"
        #   git config user.name "${{ secrets.SOCIALGROOVYBOT_NAME }}"
        #   git add CHANGELOG.md package.json
        #   git commit -m "chore(release): ${{ steps.semantic.outputs.new_release_version }} [skip ci]"
        #   git push origin ${{ github.ref }}
