name: Review

on:
  push:
    branches:
      - '**'
    tags-ignore:
      - v*

concurrency:
  cancel-in-progress: true
  group: ${{ github.ref }}

jobs:

  ##############################################################################
  ## GENERATE KUBERNETES MANIFESTS
  ##############################################################################
  manifests:
    name: Generate k8s manifests
    runs-on: ubuntu-latest
    steps:

    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Load review environment variables
      run: |
        cat ".github/review.env" >> $GITHUB_ENV

    - name: Yarn cache setup
      uses: c-hive/gha-yarn-cache@v1

    - name: Install kosko-charts autodevops
      run: |
        npx degit SocialGouv/kosko-charts#judev /tmp/kosko-charts
        cd /tmp/kosko-charts
        yarn 
        yarn build
        cd templates/nok8s
        yarn
        #cp templates/nok8s /tmp/nok8s
        #yarn --frozen-lockfile --prefer-offline

    - name: Copy application k8s config to autodevops
      run: cp -r .socialgouv/environments .socialgouv/config.json /tmp/kosko-charts/templates/nok8s/

    - name: Generate k8s manifests
      run: |
        echo SOCIALGOUV_BASE_DOMAIN: $SOCIALGOUV_BASE_DOMAIN
        cd /tmp/kosko-charts/templates/nok8s/
        yarn --silent generate:dev > manifests.yml
      env:
        SOCIALGOUV_CONFIG_PATH: /tmp/kosko-charts/templates/config.json
        SOCIALGOUV_BASE_DOMAIN: ${{ env.SOCIALGOUV_BASE_DOMAIN }}

    - name: Archive k8s manifests
      uses: actions/upload-artifact@v2
      with:
        name: manifests.yml
        path: manifests.yml
