name: Review Branch

on:
  push:
    branches:
      - '**'
    tags-ignore:
      - v*

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:

  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:

    - name: Get project name
      run: |
        echo "project=${GITHUB_REPOSITORY#*/}" >> $GITHUB_ENV

    - name: Use autodevops to deploy review branch
      uses: SocialGouv/actions/autodevops@master
      with:
        environment: dev
        project: ${{ env.project }}
        token: ${{ secrets.GITHUB_TOKEN }}
        imageName: fabrique/${{ env.project }}
        kubeconfig: ${{ secrets.SOCIALGOUV_KUBE_CONFIG_DEV }}
