name: Review

on:
  push:
    branches:
      - '**'
    tags-ignore:
      - v*

concurrency:
  cancel-in-progress: true
  group: ${{ github.ref }}

jobs:

  ##############################################################################
  ## GENERATE KUBERNETES MANIFESTS
  ##############################################################################
  manifests:
    name: Generate k8s manifests
    runs-on: ubuntu-latest
    steps:

    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Load review environment variables
      run: |
        cat ".github/review.env" >> $GITHUB_ENV

    - name: Yarn cache setup
      uses: c-hive/gha-yarn-cache@v1

    - name: Install no-k8s template
      run: |
        echo $RUNNER_TEMP
        echo "${{ github.action_path }}"
        pwd
        npx degit SocialGouv/kosko-charts/templates/nok8s#alpha /tmp/nok8s
        cd /tmp/nok8s
        cat package.json
        yarn
        ls
        yarn --cwd templates/nok8s

    - name: Copy application k8s config
      run: cp -r .socialgouv/environments .socialgouv/config.json /tmp/nok8s

    - name: Generate k8s manifests
      run: |
        echo SOCIALGOUV_BASE_DOMAIN: $SOCIALGOUV_BASE_DOMAIN
        env
        cd /tmp/nok8s/
        ls
        cat package.json
        yarn
        yarn generate:dev | grep ghcr
        yarn --silent generate:dev > ../../manifests.yml
      env:
        SOCIALGOUV_CONFIG_PATH: /tmp/nok8s/config.json
        SOCIALGOUV_BASE_DOMAIN: ${{ env.SOCIALGOUV_BASE_DOMAIN }}

    - name: Archive k8s manifests
      uses: actions/upload-artifact@v2
      with:
        name: manifests.yml
        path: manifests.yml
