name: Tag

on:
  push:
    tags:
      - v*

jobs:
  tag:
    name: Tag
    runs-on: ubuntu-latest
    steps:

      - name: Get tag
        run: echo "tag=${GITHUB_REF##*/}" >> $GITHUB_ENV

      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Test
        run: |
          echo GITHUB_SHA: ${GITHUB_SHA}
          echo GITHUB_REF: ${GITHUB_REF}
          echo GITHUB_HEAD_REF: ${GITHUB_HEAD_REF}
          echo TAG: ${{ env.tag }}
          cat package.json
