name: Tag

on:
  push:
    tags:
      - '*.*'

jobs:
  tag:
    name: Tag
    runs-on: ubuntu-latest
    steps:
      - name: Test
        run: |
          echo GITHUB_SHA: ${GITHUB_SHA}
          echo GITHUB_REF: ${GITHUB_REF}
